### PR TITLE
JIRA-004: add awesome ml feature

### PR DESCRIPTION
**Pull request by JassonRM**
New pull request of my awesome feature

### CODE REVIEW

**Comment by kennethGHS** [comment]
NGL jason, thast a pretty cool empty file

**Review by kennethGHS — CHANGES_REQUESTED** [review]
You should add a little bit more of words before uploading an empty file

**Review by m-herrera — APPROVED** [review]
Great work!

**Review by isaacporras — APPROVED** [review]
Awesome!

**Review by kennethGHS — CHANGES_REQUESTED** [review]
Thast not an awesome feature

**Pull request merged**
